variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  FF_USE_LEGACY_ARTIFACTS_UPLOAD: "true"
  SELENIUM_URL: "http://selenium-chrome:4444/wd/hub"
  ALLURE_VERSION: "2.24.0"

image: maven:3.9.6-eclipse-temurin-17

services:
  - name: selenium/standalone-chrome:latest
    alias: selenium-chrome

cache:
  paths:
    - .m2/repository
  key: "$CI_COMMIT_REF_SLUG"

stages:
  - test
  - allure
  - pages

test:
  stage: test
  script:
    - echo "🚀 Tests başlatılıyor..."
    - |
      export MAVEN_OPTS="$MAVEN_OPTS -Dselenium.grid.url=$SELENIUM_URL"
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit: 
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/
    expire_in: 1 week

allure:
  stage: allure
  image: frankescobar/allure-docker-service
  script:
    - apt-get update && apt-get install -y maven
    - mkdir -p public
    - allure generate target/allure-results -o public/allure-report || true
    - echo '<!DOCTYPE html><meta http-equiv="refresh" content="0; url=allure-report/index.html">' > public/index.html
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - test

pages:
  stage: pages
  script:
    - echo "Deploying to pages"
  artifacts:
    paths:
      - public
  dependencies:
    - allure
  only:
    - main