variables:
 MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
 FF_USE_LEGACY_ARTIFACTS_UPLOAD: "true"
 SELENIUM_URL: "http://selenium-chrome:4444/wd/hub"
 CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"
 CUCUMBER_PUBLISH_ENABLED: "true" 

image: maven:3.9.6-eclipse-temurin-17

services:
 - name: selenium/standalone-chrome:latest
   alias: selenium-chrome

cache:
 paths:
   - .m2/repository
 key: "$CI_COMMIT_REF_SLUG"

stages:
 - test
 - report
 - deploy

test:
 stage: test
 before_script:
   - apt-get update && apt-get install -y jq
 script:
   - echo "🚀 Tests başlatılıyor..."
   - echo "⚙️ Maven ayarları yapılandırılıyor..."
   - |
     export MAVEN_OPTS="$MAVEN_OPTS \
       -Dselenium.grid.url=$SELENIUM_URL \
       -Dwebdriver.chrome.whitelistedIps= \
       -Dcucumber.publish.quiet=false \
       -Dwebdriver.timeouts.implicitlywait=30000 \
       -Dwebdriver.timeouts.pageLoadTimeout=30000"

   - echo "🧪 Testler çalıştırılıyor..."
   - |
     echo "📋 Test Senaryoları:"
     echo "-------------------"
     mvn clean test -B -Dtest=TestRunner \
       -Dcucumber.plugin="pretty,usage,html:target/cucumber-reports/report.html,json:target/cucumber-reports/cucumber.json,io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm,progress,rerun:target/failed_scenarios.txt,testng:target/cucumber-reports/cucumber-results.xml" \
       -Dcucumber.execution.dry-run=false \
       -Dcucumber.execution.strict=true \
       -Dcucumber.execution.parallel.enabled=false \
       -Dcucumber.ansi-colors.disabled=false \
       -Dcucumber.filter.tags="not @ignore" \
       -Dcucumber.monochrome=false \
       -Dcucumber.pretty=true \
       -Dmaven.test.failure.ignore=true \
       -Dselenium.grid.url=$SELENIUM_URL \
       -Dcucumber.publish.enabled=true \
       -X || true

   - echo "📊 Test Sonuçları:"
   - |
     if [ -f "target/cucumber-reports/cucumber.json" ]; then
       echo ""
       echo "🔍 Test Adımları:"
       echo "---------------"
       jq -r '.[] | 
         .name as $feature |
         .elements[] |
         "Feature: \($feature)\n" +
         "  Scenario: " + .name + "\n" +
         (.steps[] | "    " + .keyword + .name + " - " + .result.status)
       ' target/cucumber-reports/cucumber.json |
       while IFS= read -r line; do
         if [[ $line == *"passed"* ]]; then
           echo "✅ ${line% - passed}"
         elif [[ $line == *"failed"* ]]; then
           echo "❌ ${line% - failed}"
         elif [[ $line == *"skipped"* ]]; then
           echo "⏭️ ${line% - skipped}"
         elif [[ $line == Feature* ]]; then
           echo "🌟 $line"
         elif [[ $line == *Scenario* ]]; then
           echo "📝 $line"
         else
           echo "$line"
         fi
       done

       echo ""
       echo "📈 Test İstatistikleri:"
       PASSED=$(jq '[.[] | .elements[] | .steps[] | select(.result.status == "passed")] | length' target/cucumber-reports/cucumber.json)
       FAILED=$(jq '[.[] | .elements[] | .steps[] | select(.result.status == "failed")] | length' target/cucumber-reports/cucumber.json)
       SKIPPED=$(jq '[.[] | .elements[] | .steps[] | select(.result.status == "skipped")] | length' target/cucumber-reports/cucumber.json)
       TOTAL=$((PASSED + FAILED + SKIPPED))
       
       echo "✅ Başarılı Adım: $PASSED / $TOTAL"
       echo "❌ Başarısız Adım: $FAILED / $TOTAL"
       echo "⏭️ Atlanan Adım: $SKIPPED / $TOTAL"
       
       # Test özeti oluştur
       {
         echo "Test Özeti"
         echo "=========="
         echo "Tarih: $(date)"
         echo "Branch: $CI_COMMIT_REF_NAME"
         echo "Commit: $CI_COMMIT_SHA"
         echo ""
         echo "Sonuçlar:"
         echo "✅ Başarılı: $PASSED / $TOTAL"
         echo "❌ Başarısız: $FAILED / $TOTAL"
         echo "⏭️ Atlanan: $SKIPPED / $TOTAL"
         
         echo ""
         echo "Detaylı Adımlar:"
         jq -r '.[] | .elements[] | .steps[] | "  " + .keyword + " " + .name + " - " + .result.status' target/cucumber-reports/cucumber.json
       } > test_summary.txt
     else
       echo "⚠️ Test sonuçları bulunamadı!"
     fi

   - echo "📋 Allure raporu oluşturuluyor..."
   - mvn allure:report || true
   - echo "✅ Test aşaması tamamlandı"

 artifacts:
   when: always
   reports:
     junit:
       - target/surefire-reports/TEST-*.xml
   paths:
     - target/allure-results/
     - target/allure-report/
     - target/cucumber-reports/
     - target/surefire-reports/
     - test_summary.txt
   expire_in: 1 week

allure-report:
 stage: report
 script:
   - echo "📁 Dizinler oluşturuluyor..."
   - mkdir -p public/cucumber-report public/allure-report
   - echo "📋 Raporlar kopyalanıyor..."
   - cp -r target/cucumber-reports/* public/cucumber-report/ || true
   - cp -r target/allure-report/* public/allure-report/ || true
   - cp test_summary.txt public/ || true
   - echo "🎨 Index sayfası oluşturuluyor..."
   - |
     cat << 'EOF' > public/index.html
     <!DOCTYPE html>
     <html>
     <head>
         <meta charset="utf-8">
         <title>🔍 Test Raporları</title>
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
         <style>
             body { 
                 font-family: Arial, sans-serif; 
                 margin: 40px;
                 background: #f5f5f5;
             }
             h1 { 
                 color: #333;
                 text-align: center;
                 margin-bottom: 30px;
             }
             .reports {
                 max-width: 600px;
                 margin: 20px auto;
                 background: white;
                 padding: 20px;
                 border-radius: 10px;
                 box-shadow: 0 2px 5px rgba(0,0,0,0.1);
             }
             .report-link {
                 display: flex;
                 align-items: center;
                 color: #0366d6;
                 text-decoration: none;
                 padding: 15px;
                 margin: 10px 0;
                 border-radius: 5px;
                 transition: all 0.3s ease;
             }
             .report-link:hover {
                 background: #f6f8fa;
                 transform: translateX(5px);
             }
             .report-link i {
                 margin-right: 10px;
                 font-size: 24px;
             }
             .dashboard {
                 display: grid;
                 grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                 gap: 20px;
                 margin-bottom: 30px;
             }
             .stat-card {
                 background: white;
                 padding: 20px;
                 border-radius: 8px;
                 text-align: center;
                 box-shadow: 0 2px 5px rgba(0,0,0,0.1);
             }
             .stat-card i {
                 font-size: 30px;
                 margin-bottom: 10px;
                 color: #0366d6;
             }
         </style>
     </head>
     <body>
         <h1>📊 Test Raporları Dashboard</h1>
         <div class="dashboard">
             <div class="stat-card">
                 <i class="fas fa-vial"></i>
                 <h3>Test Sonuçları</h3>
                 <p id="testResults">Yükleniyor...</p>
             </div>
             <div class="stat-card">
                 <i class="fas fa-code-branch"></i>
                 <h3>Branch</h3>
                 <p>${CI_COMMIT_REF_NAME}</p>
             </div>
             <div class="stat-card">
                 <i class="fas fa-clock"></i>
                 <h3>Tarih</h3>
                 <p id="currentDate"></p>
             </div>
             <div class="stat-card">
                 <i class="fas fa-check-circle"></i>
                 <h3>Test Durumu</h3>
                 <p id="testStatus">Yükleniyor...</p>
             </div>
         </div>
         <div class="reports">
             <a href="./allure-report/index.html" class="report-link">
                 <i class="fas fa-chart-bar"></i>
                 Allure Report - Detaylı Test Raporu
             </a>
             <a href="./cucumber-report/report.html" class="report-link">
                 <i class="fas fa-file-alt"></i>
                 Cucumber Report - BDD Test Sonuçları
             </a>
             <a href="./test_summary.txt" class="report-link">
                 <i class="fas fa-file-text"></i>
                 Test Özeti
             </a>
         </div>
         <script>
             document.getElementById('currentDate').textContent = new Date().toLocaleDateString();
             
             fetch('test_summary.txt')
               .then(response => response.text())
               .then(data => {
                   const lines = data.split('\n');
                   const results = lines.find(line => line.includes('✅'));
                   if (results) {
                       document.getElementById('testResults').innerHTML = results;
                   }
                   
                   const passed = parseInt(results.match(/\d+/)[0]);
                   const total = parseInt(results.match(/\d+/g)[1]);
                   const failed = total - passed;
                   
                   document.getElementById('testStatus').innerHTML = failed === 0 
                       ? '✅ Tüm Testler Başarılı'
                       : `❌ ${failed} Test Başarısız`;
               })
               .catch(() => {
                   document.getElementById('testResults').textContent = 'Sonuç Bulunamadı';
                   document.getElementById('testStatus').textContent = 'Durum Bilinmiyor';
               });
         </script>
     </body>
     </html>
     EOF
   - echo "✨ Raporlama tamamlandı"
 artifacts:
   paths:
     - public
   expire_in: 30 days
 dependencies:
   - test

pages:
 stage: deploy
 script:
   - echo "🚀 Pages dağıtımı başlıyor..."
   - echo "📦 Raporlar yayınlanıyor..."
   - echo "✅ Dağıtım tamamlandı"
 artifacts:
   paths:
     - public
   expire_in: 30 days
 dependencies:
   - allure-report
 only:
   - main