variables:
 MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
 FF_USE_LEGACY_ARTIFACTS_UPLOAD: "true"
 SELENIUM_URL: "http://selenium-chrome:4444/wd/hub"

image: maven:3.9.6-eclipse-temurin-17

services:
 - name: selenium/standalone-chrome:latest
   alias: selenium-chrome

stages:
 - test
 - report
 - deploy

test:
 stage: test
 script:
   - echo "🚀 Tests başlatılıyor..."
   - |
     export MAVEN_OPTS="$MAVEN_OPTS -Dselenium.grid.url=$SELENIUM_URL"
   - mvn clean test -e || true
 artifacts:
   when: always
   reports:
     junit: 
       - target/surefire-reports/TEST-*.xml
   paths:
     - target/
   expire_in: 1 week

report:
 stage: report
 image: 
   name: frankescobar/allure-docker-service
   entrypoint: [""]
 script:
   - allure --version
   - mkdir -p public/allure
   - allure generate target/allure-results -o public/allure --clean
   - cp -r target/cucumber-reports public/cucumber
   - |
     cat << 'EOF' > public/index.html
     <!DOCTYPE html>
     <html>
     <head>
         <meta charset="utf-8">
         <title>Test Reports</title>
         <style>
             body { font-family: Arial, sans-serif; margin: 40px; }
             h1 { color: #333; }
             .reports { margin-top: 20px; }
             a { color: #0366d6; text-decoration: none; padding: 10px; display: block; }
             a:hover { background: #f6f8fa; }
         </style>
     </head>
     <body>
         <h1>Test Raporları</h1>
         <div class="reports">
             <a href="./allure/index.html">Allure Report</a>
             <a href="./cucumber/report.html">Cucumber Report</a>
         </div>
     </body>
     </html>
     EOF
 artifacts:
   paths:
     - public
   expire_in: 1 week
 dependencies:
   - test

pages:
 stage: deploy
 script:
   - echo "Pages deploying..."
 artifacts:
   paths:
     - public
   expire_in: 30 days
 dependencies:
   - report
 only:
   - main