image: maven:17-eclipse-temurin

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  CHROME_OPTIONS: "--no-sandbox --headless --disable-dev-shm-usage"

cache:
  paths:
    - .m2/repository
  key: "$CI_COMMIT_REF_SLUG"

stages:
  - test
  - deploy

test:
  stage: test
  image: maven:17-eclipse-temurin
  tags:
    - docker
  script:
    - java -version
    - mvn -version
    - mvn clean test
    - mvn allure:report
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/allure-results
      - target/allure-report
      - target/test-logs
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH
      when: always

pages:
  stage: deploy
  dependencies:
    - test
  tags:
    - docker
  script:
    - mkdir -p public
    - cp -r target/allure-report/* public
    - |
      echo "Test Summary:" > public/summary.txt
      echo "Build: $CI_BUILD_ID" >> public/summary.txt
      echo "Branch: $CI_COMMIT_REF_NAME" >> public/summary.txt
      echo "Commit: $CI_COMMIT_SHA" >> public/summary.txt
      echo "Date: $(date)" >> public/summary.txt
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main