variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  FF_USE_LEGACY_ARTIFACTS_UPLOAD: "true"
  SELENIUM_URL: "http://selenium-chrome:4444/wd/hub"
  CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"

image: maven:3.8.1-eclipse-temurin-17

services:
  - name: selenium/standalone-chrome:latest
    alias: selenium-chrome

cache:
  paths:
    - .m2/repository
  key: "$CI_COMMIT_REF_SLUG"

stages:
  - test
  - report
  - deploy

test:
  stage: test
  script:
    - echo "🚀 Tests başlatılıyor..."
    - echo "⚙️ Maven ayarları yapılandırılıyor..."
    - |
      export MAVEN_OPTS="$MAVEN_OPTS \
        -Dselenium.grid.url=$SELENIUM_URL \
        -Dwebdriver.chrome.whitelistedIps= \
        -Dcucumber.publish.quiet=true \
        -Dwebdriver.timeouts.implicitlywait=30000 \
        -Dwebdriver.timeouts.pageLoadTimeout=30000"

    - echo "🧪 Testler çalıştırılıyor..."
    - mvn clean test -Dtest=TestRunner \
      -Dcucumber.plugin="pretty,html:target/cucumber-reports/report.html,json:target/cucumber-reports/cucumber.json,io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm" \
      -Dselenium.grid.url=$SELENIUM_URL || true
    - echo "📊 Allure raporu oluşturuluyor..."
    - mvn allure:report || true
    - echo "✅ Test aşaması tamamlandı"

  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/allure-results/
      - target/allure-report/
      - target/cucumber-reports/
      - target/surefire-reports/
    expire_in: 1 week

allure-report:
  stage: report
  script:
    - echo "📁 Dizinler oluşturuluyor..."
    - mkdir -p public/cucumber-report public/allure-report
    - echo "📋 Raporlar kopyalanıyor..."
    - cp -r target/cucumber-reports/* public/cucumber-report/ || true
    - cp -r target/allure-report/* public/allure-report/ || true
    - echo "🎨 Index sayfası oluşturuluyor..."
    - |
      cat << 'EOF' > public/index.html
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="utf-8">
          <title>🔍 Test Raporları</title>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
          <style>
              body { 
                  font-family: Arial, sans-serif; 
                  margin: 40px;
                  background: #f5f5f5;
              }
              h1 { 
                  color: #333;
                  text-align: center;
                  margin-bottom: 30px;
              }
              .reports {
                  max-width: 600px;
                  margin: 20px auto;
                  background: white;
                  padding: 20px;
                  border-radius: 10px;
                  box-shadow: 0 2px 5px rgba(0,0,0,0.1);
              }
              .report-link {
                  display: flex;
                  align-items: center;
                  color: #0366d6;
                  text-decoration: none;
                  padding: 15px;
                  margin: 10px 0;
                  border-radius: 5px;
                  transition: all 0.3s ease;
              }
              .report-link:hover {
                  background: #f6f8fa;
                  transform: translateX(5px);
              }
              .report-link i {
                  margin-right: 10px;
                  font-size: 24px;
              }
              .dashboard {
                  display: grid;
                  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                  gap: 20px;
                  margin-bottom: 30px;
              }
              .stat-card {
                  background: white;
                  padding: 20px;
                  border-radius: 8px;
                  text-align: center;
                  box-shadow: 0 2px 5px rgba(0,0,0,0.1);
              }
              .stat-card i {
                  font-size: 30px;
                  margin-bottom: 10px;
                  color: #0366d6;
              }
          </style>
      </head>
      <body>
          <h1>📊 Test Raporları Dashboard</h1>
          <div class="dashboard">
              <div class="stat-card">
                  <i class="fas fa-vial"></i>
                  <h3>Test Sonuçları</h3>
                  <p>${CI_JOB_NAME}</p>
              </div>
              <div class="stat-card">
                  <i class="fas fa-code-branch"></i>
                  <h3>Branch</h3>
                  <p>${CI_COMMIT_REF_NAME}</p>
              </div>
              <div class="stat-card">
                  <i class="fas fa-clock"></i>
                  <h3>Tarih</h3>
                  <p id="currentDate"></p>
              </div>
          </div>
          <div class="reports">
              <a href="./allure-report/index.html" class="report-link">
                  <i class="fas fa-chart-bar"></i>
                  Allure Report - Detaylı Test Raporu
              </a>
              <a href="./cucumber-report/report.html" class="report-link">
                  <i class="fas fa-file-alt"></i>
                  Cucumber Report - BDD Test Sonuçları
              </a>
          </div>
          <script>
              document.getElementById('currentDate').textContent = new Date().toLocaleDateString();
          </script>
      </body>
      </html>
      EOF
    - echo "✨ Raporlama tamamlandı"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  dependencies:
    - test

pages:
  stage: deploy
  script:
    - echo "🚀 Pages dağıtımı başlıyor..."
    - echo "📦 Raporlar yayınlanıyor..."
    - echo "✅ Dağıtım tamamlandı"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  dependencies:
    - allure-report
  only:
    - main