variables:
 MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
 SELENIUM_URL: "http://selenium-chrome:4444/wd/hub"
 CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"

image: maven:3.9.6-eclipse-temurin-17

services:
 - name: selenium/standalone-chrome:latest
   alias: selenium-chrome

cache:
 paths:
   - .m2/repository
 key: "$CI_COMMIT_REF_SLUG"

stages:
 - test
 - report
 - deploy

test:
 stage: test
 script:
   - |
     mvn clean test \
       -Dtest=TestRunner \
       -Dcucumber.plugin="pretty,json:target/cucumber-reports/cucumber.json,io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm" \
       -Dselenium.grid.url=$SELENIUM_URL \
       -Dwebdriver.chrome.arguments="$CHROME_OPTIONS"
 artifacts:
   when: always
   reports:
     junit: target/surefire-reports/TEST-*.xml
   paths:
     - target/allure-results/
     - target/cucumber-reports/
     - target/surefire-reports/

allure-report:
 stage: report
 script:
   - mvn allure:report
   - mkdir -p public
   - cp -r target/allure-report/* public/
 artifacts:
   paths:
     - public
 dependencies:
   - test

pages:
 stage: deploy
 script:
   - echo "Allure raporu yayınlanıyor..."
 artifacts:
   paths:
     - public
 dependencies:
   - allure-report
 only:
   - main
