name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Tests with Allure
      run: mvn clean test
      
    - name: Generate Allure Report
      run: mvn allure:report
      
    - name: Store Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven-plugin
    
    - name: Deploy
      if: github.ref == 'refs/heads/main' && success()
      run: |
        echo "Deploying to production..."
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 