name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SELENIUM_URL: "http://localhost:4444/wd/hub"
  CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size="2g"

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Wait for Selenium Grid
      run: |
        echo "🔍 Selenium Grid bağlantısı kontrol ediliyor..."
        timeout 60s bash -c 'until curl -s -f "http://localhost:4444/wd/hub/status" > /dev/null; do echo "⏳ Selenium Grid başlatılıyor..."; sleep 2; done'
        echo "✅ Selenium Grid hazır!"

    - name: Run Tests
      run: |
        echo "🚀 Tests başlatılıyor..."
        mvn clean test -Dtest=TestRunner \
          -Dcucumber.plugin="pretty,\
          html:target/cucumber-reports/report.html,\
          json:target/cucumber-reports/cucumber.json,\
          io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm,\
          rerun:target/cucumber-reports/rerun.txt" \
          -Dallure.results.directory=target/allure-results \
          -Dselenium.grid.url=$SELENIUM_URL \
          -Dwebdriver.chrome.arguments="$CHROME_OPTIONS"

    - name: Generate Allure Report
      run: |
        mvn allure:report
      if: always()

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: |
          target/allure-results/
          target/allure-report/
          target/cucumber-reports/
          target/surefire-reports/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/allure-report 